/* eslint-disable prettier/prettier */
// settings
export const LOADER = 'LOADER';
export const NFC = 'NFC';
export const LANG = 'LANG';
export const HELP = 'HELP';
export const FORGOT_PASS_SUCESS = 'FORGOT_PASS_SUCESS';
export const FORGOT_PASS_ERROR = 'FORGOT_PASS_ERROR';
export const RESET_PASS_INFO = 'RESET_PASS_INFO';
export const LOCATIONS = 'LOCATIONS';
export const BACK_PAGE_MOUNT = 'BACK_PAGE_MOUNT';
export const NEXT_PAGE_MOUNT = 'NEXT_PAGE_MOUNT';
export const NFC_FOR_MOUNTING = 'NFC_FOR_MOUNTING';
export const MOUNT_CAMERA_LIST = 'MOUNT_CAMERA_LIST';
export const CHANGE_IS_MULTYPLE = 'CHANGE_IS_MULTYPLE';
export const LOCATION_MAIN = 'LOCATION_MAIN';
export const LOCATTION_LOC = 'LOCATTION_LOC';

// auth
export const LOGUT = 'LOGUT';
export const USER_ROLE = 'USER_ROLE';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const CHANGE_STATUS_LOAD = 'CHANGE_STATUS_LOAD';
export const CHANGE_STATUS_ERROR = 'CHANGE_STATUS_ERROR';
export const GET_COMPANY_INFO = 'GET_COMPANY_INFO';
export const GET_COMPANY_INFO_ERROR = 'GET_COMPANY_INFO_ERROR';
export const LOGIN_WITH_GOOGLE_ACCOUNT = 'LOGIN_WITH_GOOGLE_ACCOUNT';
export const LOGIN_WITH_GOOGLE_ACCOUNT_ERROR =
  'LOGIN_WITH_GOOGLE_ACCOUNT_ERROR';

// scan
export const SAVE_CURRENT_SEARCH = 'SAVE_CURRENT_SEARCH';
export const CLEAN_SCAN = 'CLEAN_SCAN';
export const SAVE_CURRENT_SEARCH_ERROR = 'SAVE_CURRENT_SEARCH_ERROR';
export const SAVE_CURRENT_SCAN = 'SAVE_CURRENT_SCAN';
export const ALLOW_NEW_SCAN = 'ALLOW_NEW_SCAN';
export const SAVE_CURRENT_SCAN_INFO = 'SAVE_CURRENT_SCAN_INFO';
export const SAVE_GIVE_ITEM_INFO_LIST = 'SAVE_GIVE_ITEM_INFO_LIST';
export const CLEAR_SCAN_GIVE_LIST = 'CLEAR_SCAN_GIVE_LIST';
export const UPDATE_SCAN_GIVE_LIST = 'UPDATE_SCAN_GIVE_LIST';
export const ERROR_CURRENT_SCAN_INFO = 'ERROR_CURRENT_SCAN_INFO';
export const DIALOG_INPUT = 'DIALOG_INPUT';
export const CHANGE_ALL_IS_OPEN = 'CHANGE_ALL_IS_OPEN';
export const MOUNT_SCAN = 'MOUNT_SCAN';
export const ERROR_CURRENT_MOUNT_SCAN_INFO = 'ERROR_CURRENT_MOUNT_SCAN_INFO';
export const SAVE_CURRENT_MOUNT_SCAN_INFO_LIST =
  'SAVE_CURRENT_MOUNT_SCAN_INFO_LIST';

//moveToObject
export const SET_IS_MOVE_SCANER = 'SET_IS_MOVE_SCANER';
export const SET_IS_ADD_MOVE = 'SET_IS_ADD_MOVE';
export const CHOOSED_MOVE_USER = 'CHOOSED_MOVE_USER';
export const SET_SCANED_MOVE_ITEM = 'SET_SCANED_MOVE_ITEM';
export const SAVE_MOVE_LOCATIONS = 'SAVE_MOVE_LOCATIONS';
export const CLEAN_MOVE_TO_OBJECT = 'CLEAN_MOVE_TO_OBJECT';
export const MOVE_TO_OBJECT_ERROR = 'MOVE_TO_OBJECT_ERROR';
export const IS_ROLE_ALLOW = 'IS_ROLE_ALLOW';
export const DELETE_MOVE_ITEM = 'DELETE_MOVE_ITEM';
export const CHANGE_QUANTITY = 'CHANGE_QUANTITY';


// services
export const SUCCES_IN_SERVICES = 'SUCCES_IN_SERVICES';
export const ERROR_SEND_SERVICES = 'ERROR_SEND_SERVICES';
export const PUT_ERROR_SEND_SERVICES = 'PUT_ERROR_SEND_SERVICES';

// writeoff
export const SUCCES_WRITE_OFF = 'SUCCES_WRITE_OFF';
export const ERROR_WRITE_OFF = 'ERROR_WRITE_OFF';
export const PUT_ERROR_WRITE_OFF = 'PUT_ERROR_WRITE_OFF';

// marking
export const MARKING = 'MARKING';
export const CLEAR_MARKING = 'CLEAR_MARKING';
export const MARKING_ERROR = 'MARKING_ERROR';
export const MARKING_ERROR_DONE = 'MARKING_ERROR_DONE';
export const MAKE_MARKING_ERROR_DEFAULT = 'MAKE_MARKING_ERROR_DEFAULT';
export const MARKING_CURRENT_ID = 'MARKING_CURRENT_ID';
export const MARKING_SEARCH = 'MARKING_SEARCH';
export const CHANGE_STATUS_LOAD_MORE = 'CHANGE_STATUS_LOAD_MORE';

//on me
export const GET_MY_ITEMS = 'GET_MY_ITEMS';
export const GET_MY_ITEMS_SEARCH = 'GET_MY_ITEMS_SEARCH';
export const GET_MY_ITEMS_ERROR = 'GET_MY_ITEMS_ERROR';
export const CHANGE_STATUS_MY_LOAD_MORE = 'CHANGE_STATUS_MY_LOAD_MORE';
export const MY_CURRENT_INFO_ID = 'MY_CURRENT_INFO_ID';
export const SET_MY_CURRENT_INFO = 'SET_MY_CURRENT_INFO';
export const SET_IS_SHOW_FILTER = 'SET_IS_SHOW_FILTER';

// transactions
export const TRANSACTIONS_LIST = 'TRANSACTIONS_LIST';
export const TRANSACTIONS_ERROR = 'TRANSACTIONS_ERROR';
export const LOAD_MORE_TRANSACTIONS = 'LOAD_MORE_TRANSACTIONS';
export const CLEAR_TRANSACTIONS_LIST = 'CLEAR_TRANSACTIONS_LIST';

// give
export const SET_GIVE_ITEM_QTY = 'SET_GIVE_ITEM_QTY';
export const CLEAR_GIVE_ITEM_QTY = 'CLEAR_GIVE_ITEM_QTY';
export const GET_USERS = 'GET_USERS';
export const CLEAR_USER_LIST = 'CLEAR_USER_LIST';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
export const USER_CURRENT_ID = 'USER_CURRENT_ID';
export const TRANSFER = 'TRANSFER';
export const ERROR_TRANSFER = 'ERROR_TRANSFER';

// transfers
export const TRANSFERS_LIST = 'TRANSFERS_LIST';
export const TRANSFERS_ERROR = 'TRANSFERS_ERROR';
export const LOAD_MORE_TRANSFERS = 'LOAD_MORE_TRANSFERS';
export const CLEAR_TRANSFERS_LIST = 'CLEAR_TRANSFERS_LIST';
export const TRANSFERS_ID = 'TRANSFERS_ID';
export const TRANSFERS_UPDATE = 'TRANSFERS_UPDATE';
export const TRANSFERS_UPDATE_ERROR = 'TRANSFERS_UPDATE_ERROR';

// accept
export const GET_BID_LIST = 'GET_BID_LIST';
export const GET_BID_LIST_ERROR = 'GET_BID_LIST_ERROR';
export const LOAD_MORE_STATUS = 'LOAD_MORE_STATUS';
export const CLEAR_BID_LIST = 'CLEAR_BID_LIST';
export const SAVE_USER_ACCEPT_BID = 'SAVE_USER_ACCEPT_BID';
export const ALREADY_SCANNED_BIDS = 'ALREADY_SCANNED_BIDS';
export const MAKE_ACCEPT = 'MAKE_ACCEPT';
export const MAKE_ACCEPT_ERROR = 'MAKE_ACCEPT_ERROR';
export const SHOW_BUTTON_STATUS = 'SHOW_BUTTON_STATUS';

// inventory
export const SAVE_INVENTORY_SCANS = 'SAVE_INVENTORY_SCANS';
export const SAVE_CURRENT_INVENTORY_USER = 'SAVE_CURRENT_INVENTORY_USER';
export const SET_INVENTORY_ITEM_QTY = 'SET_INVENTORY_ITEM_QTY';
export const CLEAR_INVENTORY = 'CLEAR_INVENTORY';
export const SAVE_INVENTORY_CREATED_ITEM = 'SAVE_INVENTORY_CREATED_ITEM';

// stocktaking
export const MAKE_STOCKTAKING = 'MAKE_STOCKTAKING';
export const MAKE_STOCKTAKING_ERROR = 'MAKE_STOCKTAKING_ERROR';

// comments
export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR';
export const CHANGE_STATUS_LOAD_MORE_COMMENTS =
  'CHANGE_STATUS_LOAD_MORE_COMMENTS';
export const CLEAR_COMMENTS = 'CLEAR_COMMENTS';
export const SEND_COMMENT = 'SEND_COMMENT';
export const SEND_COMMENT_ERROR = 'SEND_COMMENT_ERROR';
export const ADD_PHOTOS_TO_COMMENT = 'ADD_PHOTOS_TO_COMMENT';
export const DELETE_PHOTOS_FROM_COMMENT = 'DELETE_PHOTOS_FROM_COMMENT';

// start page
export const START_PAGE = 'START_PAGE';

//company
export const SEARCH_MY_COMPANY_ITEMS = 'SEARCH_MY_COMPANY_ITEMS';
export const SEARCH_MY_COMPANY_ITEMS_ERROR = 'SEARCH_MY_COMPANY_ITEMS_ERROR';
export const GET_COUNT_MY_COMPANY_ITEMS = 'GET_COUNT_MY_COMPANY_ITEMS';
export const GET_COUNT_MY_COMPANY_ITEMS_ERROR =
  'GET_COUNT_MY_COMPANY_ITEMS_ERROR';

//mount
export const SET_CURRENT_MOUNT_PARENT = 'SET_CURRENT_MOUNT_PARENT';
export const ADD_ITEM_TO_MOUNT_LIST = 'ADD_ITEM_TO_MOUNT_LIST';
export const DELETE_ITEM_FROM_MOUNT_LIST = 'DELETE_ITEM_FROM_MOUNT_LIST';
export const SET_ITEM_QTY_FOR_MOUNT = 'SET_ITEM_QTY_FOR_MOUNT';
export const MOUNT_ITEMS = 'MOUNT_ITEMS';
export const MOUNT_ITEMS_ERROR = 'MOUNT_ITEMS_ERROR';
export const CLEAN_MOUNT_ITEMS_LIST = 'CLEAN_MOUNT_ITEMS_LIST';

//add photo
export const ADD_PHOTO_TO_ITEM = 'ADD_PHOTO_TO_ITEM';
export const ADD_PHOTO_TO_ITEM_ERROR = 'ADD_PHOTO_TO_ITEM_ERROR';
export const SET_GO_BACK_PAGE_GALLERY = 'SET_GO_BACK_PAGE_GALLERY';
export const DELETE_PHOTO_FROM_ITEM = 'DELETE_PHOTO_FROM_ITEM';
export const DELETE_PHOTO_FROM_ITEM_ERROR = 'DELETE_PHOTO_FROM_ITEM_ERROR';

//create item
export const SAVE_BASE_ITEM_INFO = 'SAVE_BASE_ITEM_INFO';
export const SAVE_ACCOUNT_AND_VALUE = 'SAVE_ACCOUNT_AND_VALUE';
export const SAVE_PHOTO = 'SAVE_PHOTO';
export const SAVE_ADDITIONAL_INFO = 'SAVE_ADDITIONAL_INFO';
export const SAVE_ITEM_LOCATIONS = 'SAVE_ITEM_LOCATIONS';
export const SAVE_RESPONSIBLE = 'SAVE_RESPONSIBLE';
export const CREATE_ITEM = 'CREATE_ITEM ';
export const CREATE_ITEM_ERROR = 'CREATE_ITEM_ERROR';
export const CREATE_USER_ITEM = 'CREATE_USER_ITEM_';
export const CREATE_USER_ITEM_ERROR = 'CREATE_USER_ITEM_ERROR';
export const CLEAN_CREATE_ITEM = 'CLEAN_CREATE_ITEM';

//get autocomplete
export const GET_ITEM_TITLE = 'CREATE_USER_ITEM_';
export const GET_ITEM_TITLE_ERROR = 'CREATE_USER_ITEM_ERROR';
export const GET_ITEM_TYPE = 'CREATE_USER_ITEM_';
export const GET_ITEM_TYPE_ERROR = 'CREATE_USER_ITEM_ERROR';
export const GET_ITEM_BRAND = 'CREATE_USER_ITEM_';
export const GET_ITEM_BRAND_ERROR = 'CREATE_USER_ITEM_ERROR';
export const GET_ITEM_MODEL = 'CREATE_USER_ITEM_';
export const GET_ITEM_MODEL_ERROR = 'CREATE_USER_ITEM_ERROR';

export const SEARCH_ITEMS = 'SEARCH_ITEMS';
export const SEARCH_ITEMS_ERROR = 'SEARCH_ITEMS_ERROR';
export const CLEAN_SEARCH_RESULT = 'CLEAN_SEARCH_RESULT';
export const GET_SEARCH_ITEMS = 'GET_SEARCH_ITEMS';

//filters
export const SET_FILTERS = 'SET_FILTERS';
export const SET_QUERY = 'SET_QUERY';

