/* eslint-disable prettier/prettier */
// settings
export const LOADER = 'LOADER';
export const LANG = 'LANG';
export const HELP = 'HELP';
export const FORGOT_PASS_SUCESS = 'FORGOT_PASS_SUCESS';
export const FORGOT_PASS_ERROR = 'FORGOT_PASS_ERROR';
export const RESET_PASS_INFO = 'RESET_PASS_INFO';
// auth
export const LOGUT = 'LOGUT';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const CHANGE_STATUS_LOAD = 'CHANGE_STATUS_LOAD';
export const CHANGE_STATUS_ERROR = 'CHANGE_STATUS_ERROR';

// scan
export const SAVE_CURRENT_SCAN = 'SAVE_CURRENT_SCAN';
export const ALLOW_NEW_SCAN = 'ALLOW_NEW_SCAN';
export const SAVE_CURRENT_SCAN_INFO = 'SAVE_CURRENT_SCAN_INFO';
export const SAVE_CURRENT_SCAN_INFO_LIST = 'SAVE_CURRENT_SCAN_INFO_LIST';
export const CLEAR_SCAN_GIVE_LIST = 'CLEAR_SCAN_GIVE_LIST';
export const UPDATE_SCAN_GIVE_LIST = 'UPDATE_SCAN_GIVE_LIST';
export const ERROR_CURRENT_SCAN_INFO = 'ERROR_CURRENT_SCAN_INFO';
export const DIALOG_INPUT = 'DIALOG_INPUT';
export const CHANGE_ALL_IS_OPEN = 'CHANGE_ALL_IS_OPEN';

// services
export const SUCCES_IN_SERVICES = 'SUCCES_IN_SERVICES';
export const ERROR_SEND_SERVICES = 'ERROR_SEND_SERVICES';
export const PUT_ERROR_SEND_SERVICES = 'PUT_ERROR_SEND_SERVICES';

// writeoff
export const SUCCES_WRITE_OFF = 'SUCCES_WRITE_OFF';
export const ERROR_WRITE_OFF = 'ERROR_WRITE_OFF';
export const PUT_ERROR_WRITE_OFF = 'PUT_ERROR_WRITE_OFF';

// marking
export const MARKING = 'MARKING';
export const CLEAR_MARKING = 'CLEAR_MARKING';
export const MARKING_ERROR = 'MARKING_ERROR';
export const MARKING_ERROR_DONE = 'MARKING_ERROR_DONE';
export const MAKE_MARKING_ERROR_DEFAULT = 'MAKE_MARKING_ERROR_DEFAULT';
export const MARKING_CURRENT_ID = 'MARKING_CURRENT_ID';
export const MARKING_SEARCH = 'MARKING_SEARCH';
export const CHANGE_STATUS_LOAD_MORE = 'CHANGE_STATUS_LOAD_MORE';

//on me
export const GET_MY_ITEMS = 'GET_MY_ITEMS';
export const GET_MY_ITEMS_SEARCH = 'GET_MY_ITEMS_SEARCH';
export const GET_MY_ITEMS_ERROR = 'GET_MY_ITEMS_ERROR';
export const CHANGE_STATUS_MY_LOAD_MORE = 'CHANGE_STATUS_MY_LOAD_MORE';
export const MY_CURRENT_INFO_ID = 'MY_CURRENT_INFO_ID';

// transactions
export const TRANSACTIONS_LIST = 'TRANSACTIONS_LIST';
export const TRANSACTIONS_ERROR = 'TRANSACTIONS_ERROR';
export const LOAD_MORE_TRANSACTIONS = 'LOAD_MORE_TRANSACTIONS';
export const CLEAR_TRANSACTIONS_LIST = 'CLEAR_TRANSACTIONS_LIST';

// give
export const GET_USERS = 'GET_USERS';
export const CLEAR_USER_LIST = 'CLEAR_USER_LIST';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
export const USER_CURRENT_ID = 'USER_CURRENT_ID';
export const TRANSFER = 'TRANSFER';
export const ERROR_TRANSFER = 'ERROR_TRANSFER';

// transfers
export const TRANSFERS_LIST = 'TRANSFERS_LIST';
export const TRANSFERS_ERROR = 'TRANSFERS_ERROR';
export const LOAD_MORE_TRANSFERS = 'LOAD_MORE_TRANSFERS';
export const CLEAR_TRANSFERS_LIST = 'CLEAR_TRANSFERS_LIST';
export const TRANSFERS_ID = 'TRANSFERS_ID';
export const TRANSFERS_UPDATE = 'TRANSFERS_UPDATE';
export const TRANSFERS_UPDATE_ERROR = 'TRANSFERS_UPDATE_ERROR';

// accept
export const GET_BID_LIST = 'GET_BID_LIST';
export const GET_BID_LIST_ERROR = 'GET_BID_LIST_ERROR';
export const LOAD_MORE_STATUS = 'LOAD_MORE_STATUS';
export const CLEAR_BID_LIST = 'CLEAR_BID_LIST';
export const SAVE_USER_ACCEPT_BID = 'SAVE_USER_ACCEPT_BID';
export const ALREADY_SCANNED_BIDS = 'ALREADY_SCANNED_BIDS';
export const MAKE_ACCEPT = 'MAKE_ACCEPT';
export const MAKE_ACCEPT_ERROR = 'MAKE_ACCEPT_ERROR';
export const SHOW_BUTTON_STATUS = 'SHOW_BUTTON_STATUS';

// inventory
export const SAVE_INVENTORY_SCANS = 'SAVE_INVENTORY_SCANS';
export const SAVE_CURRENT_INVENTORY_USER = 'SAVE_CURRENT_INVENTORY_USER';

// stocktaking
export const MAKE_STOCKTAKING = 'MAKE_STOCKTAKING';
export const MAKE_STOCKTAKING_ERROR = 'MAKE_STOCKTAKING_ERROR';

// comments
export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR';
export const CHANGE_STATUS_LOAD_MORE_COMMENTS = 'CHANGE_STATUS_LOAD_MORE_COMMENTS';
export const CLEAR_COMMENTS = 'CLEAR_COMMENTS';
export const SEND_COMMENT = 'SEND_COMMENT';
export const SEND_COMMENT_ERROR = 'SEND_COMMENT_ERROR';
